### ISSUE TITLE
Not working in new Reactjs Version

### ISSUE THREAD

**Issue by Writtscher** [alpertuna/react-metismenu#3]
I'm using the new react version and my simple example throws the https://fb.me/react-refs-must-have-owner error. Too bad :pensive:

```
import React from 'react';
import ReactDOM from 'react-dom';
import MetisMenu from 'react-metismenu';

ReactDOM.render(
    <MetisMenu content={[
        {icon: 'icon-class-name', label: 'Dashboard', href: '/'}
    ]} />,
    document.getElementById('application'));

```

**Comment by alpertuna** [comment]
@Writtscher Thanks for the report
Probably, it is a multiple (conflicting) copies of React loaded problem.
I will look into it.

**Comment by Writtscher** [comment]
@alpertuna 

Well, thank you for your quick answer. I'm pretty sure this is an easy fix as you are not the first vendor providing a react component :smirk:.

I'll check this tomorrow as well as I'm interested what the solution is. It's very late already to dive into it.

**Comment by Writtscher** [comment]
I've checked your source code and your Item.js is probably causing this issue as you are using the **ref** attribute inside the render method. As you can read here

https://facebook.github.io/react/docs/more-about-refs.html

It is considered as bad practice to use **ref** there.

**Comment by alpertuna** [comment]
That is not a fancy ref usage, ordinary usage :). I tried and everything is expected. Can you let me know your browser module compiler configuration?

**Comment by alpertuna** [comment]
Ok, after updating dependencies, i got the same error, sorry for that.
Tomorrow I suppose to solve the problem.

**Comment by alpertuna** [comment]
I got the problem and I think it is done now.
It takes me a lot of time but problem was simple. In module's `package.json`, `react` was under `dependencies` but it should be under `peerDependencies`. Since, it installs react as a sub module, and with your react, there were two reacts. So they conflicted. When I put it under `peerDependicies`, it does not install it as a sub module and inform you to install it. After then it uses your installed module, not its own sub module.
I have published it to npm register as well, you can install with npm.

**Comment by Writtscher** [comment]
Nice one. Thank you for that. I'll use it in my project and will push pull requests as soon as something is missing ;). I've already some points that might be missing.

**Comment by alpertuna** [comment]
Ok I will be waiting for requests :)
