### ISSUE TITLE
Large build size

### ISSUE THREAD

**Issue by sapkra** [alpertuna/react-metismenu#31]
What's the reason for the extremely large file size? After the implementation my webpack build is 40kb larger.

**Comment by alpertuna** [comment]
`react-metismenu` has quite few dependencies; `classnames`, `react-redux`, `redux` and `simple-ajax`. And source code is also not that much. If your project's and `react-metismenu`'s dependencies and versions of them are not common, this may cause that because of gathering dependencies and subdependencies of it togetger. Also build environment is important that should fit production procedures.
Furthermore, 40kb is not tat extremely large :blush:
